packages:
  - "apps/*"
  - "packages/*"

catalogs:
  default:
    react: "^19.2.3"
    react-dom: "^19.2.3"
    typescript: "^5.7.3"
    "@types/react": "^19"
    "@types/react-dom": "^19"
    "@types/node": "^22.10.7"
    tailwindcss: "4.1.18"
    postcss: "^8"
    storybook: "^10.1.11"
    "@biomejs/biome": "latest"
    convex: "^1.31.5"
