/// <reference types="next/image-types/global" />

// Declares the static asset modules (`*.png`, `*.jpg`, `*.svg`, …) that
// `next/image` accepts as an imported `StaticImageData`.
//
// Next normally supplies this same reference through `next-env.d.ts` — but that
// file is generated by `next dev` / `next build` and is gitignored, so it does
// not exist in a fresh checkout. `pnpm typecheck` runs before any build in CI,
// which made `tsc --noEmit` fail on the image imports in
// `components/landing/built-with.tsx` with TS2307 while passing on every
// developer machine that had already run a build.
//
// Keeping the reference in a tracked file makes typecheck self-contained: it no
// longer depends on build output existing first. Do not delete this in favour of
// `next-env.d.ts` — duplicating the reference is harmless, and this is the only
// copy CI ever sees.
